ListPays = {
    "Afghanistan": "Kaboul",
    "Afrique du Sud": "Pretoria",
    "Albanie": "Tirana",
    "Algérie": "Alger",
    "Allemagne": "Berlin",
    "Andorre": "Andorre-la-Vieille",
    "Angola": "Luanda",
    "Anguilla": "The Valley",
    "Antarctique": "None",
    "Antigua-et-Barbuda": "Saint John's",
    "Arabouuie saoudite": "Riyadh",
    "Argentine": "Buenos Aires",
    "Arménie": "Erevan",
    "Australie": "Canberra",
    "Autriche": "Vienne",
    "Azerbaïdjan": "Bakou",
    "Bahamas": "Nassau",
    "Bahreïn": "Manama",
    "Bangladesh": "Dhaka",
    "Barbade": "Bridgetown",
    "Biélorussie": "Minsk",
    "Belgique": "Bruxelles",
    "Belize": "Belmopan",
    "Benin": "Porto-Novo",
    "Bermudes": "Hamilton",
    "Bhoutan": "Thimphou",
    "Bolivie": "La Paz",
    "Bosnie-Herzégovine": "Sarajevo",
    "Botswana": "Gaborone",
    "Brésil": "Brasília",
    "Brunei": "Bandar Seri Begawan",
    "Bulgarie": "Sofia",
    "Burkina Faso": "Ouagadougou",
    "Burundi": "Gitega",
    "Cambodge": "Phnom Penh",
    "Cameroun": "Yaoundé",
    "Canada": "Ottawa",
    "Cap-Vert": "Praia",
    "République centrafricaine": "Bangui",
    "Chili": "Santiago",
    "Chine": "Pékin",
    "Chypre": "Nicosie",
    "Colombie": "Bogotá",
    "Comores": "Moroni",
    "Congo-Brazzaville": "Brazzaville",
    "Congo-Kinshasa": "Kinshasa",
    "Corée du Nord": "Pyongyang",
    "Corée du Sud": "Séoul",
    "Costa Rica": "San José",
    "Côte d'Ivoire": "Yamoussoukro",
    "Croatie": "Zagreb",
    "Cuba": "La Havane",
    "Chypre": "Nicosie",
    "République tchèque": "Prague",
    "Danemark": "Copenhague",
    "Djibouti": "Djibouti",
    " Dominique": "Roseau",
    "Égypte": "Le Caire",
    "El Salvador": "San Salvador",
    "Équateur": "Quito",
    "Érythrée": "Asmara",
    "Estonie": "Tallinn",
    "Éthiopie": "Addis-Abeba",
    "Îles Salomon": "Honiara",
    "Îles Fidji": "Suva",
    "Finlande": "Helsinki",
    "France": "Paris",
    "Gabon": "Libreville",
    "Gambie": "Banjul",
    "Géorgie": "Tbilissi",
    "Allemagne": "Berlin",
    "Ghana": "Accra",
    "Grèce": "Athènes",
    "Grenade": "Saint George's",
    "Guatemala": "Guatemala",
    "Guinée": "Conakry",
    "Guinée-Bissau": "Bissau",
    "Guinée équatoriale": "Malabo",
    "Guyana": "Georgetown",
    "Haïti": "Port-au-Prince",
    "Honduras": "Tegucigalpa",
    "Hongrie": "Budapest",
    "Islande": "Reykjavik",
    "Inde": "New Delhi",
    "Indonésie": "Jakarta",
    "Iran": "Téhéran",
    "Irak": "Bagdad",
    "Irland: ":"DUBLIN",
    "ISLANDE: ":"REYKJAVIK",
    "Israël": "Jérusalem",
    "Italie": "Rome",
    "Jamaïque": "Kingston",
    "Japon": "Tokyo",
    "Jordanie": "Amman",
    "Kazakhstan": "Noursoultan",
    "Kenya": "Nairobi",
    "Kirghizistan": "Bichkek",
    "Kiribati": "Tarawa Atoll",
    "Koweit": "Koweït",
    "Laos": "Vientiane",
    "Lesotho": "Maseru",
    "Lettonie": "Riga",
    "Liban": "Beyrouth",
    "Liberia": "Monrovia",
    "Libye": "Tripoli",
    "Liechtenstein": "Vaduz",
    "Lituanie": "Vilnius",
    "Luxembourg": "Luxembourg",
    "Macédoine du Nord": "Skopje",
    "Madagascar": "Antananarivo",
    "Malawi": "Lilongwe",
    "Malaisie": "Kuala Lumpur",
    "Maldives": "Male",
    "Mali": "Bamako",
    "Malte": "La Valette",
    "Marshall": "Majuro",
    "Maurice": "Port Louis",
    "Mauritanie": "Nouakchott",
    "Mexique": "Mexico",
    "Micronésie: ": "Palikir",
    "Moldavie: ": "Chisinau",
    "Monaco: ": "Monaco",
    "Mongolie: ": "Oulan-Bator",
    "Monténégro: ": "Podgorica",
    "Maroc: ": "Rabat",
    "Mozambique: ": "Maputo",
    "Myanmar: ": "Nay Pyi Taw",
    "Namibie: ": "Windhoek",
    "Nauru: ": "Nour",
    "Népal: ": "Katmandou",
    "Nicaragua: ": "Managua",
    "Niger: ": "Niamey",
    "Nigeria: ": "Abuja",
    "Norvège: ": "Oslo",
    "Oman: ": "Mascate",
    "Pakistan: ": "Islamabad",
    "Palaos: ": "Melekeok",
    "Palestine: ": "Ramallah",
    "Panama: ": "Panama",
    "Papouasie-Nouvelle-Guinée: ": "Port Moresby",
    "Paraguay :": "Asuncion",
    "Pérou: ": "Lima",
    "Philippines: ": "Manille",
    "Pologne: ": "Varsovie",
    "Portugal: ": "Lisbonne",
    "Qatar: ": "Doha",
    "République centrafricaine: ":"Bangui",
    "République dominicaine: ":"Saint-Domingue",
    "Roumanie: ": "Bucarest",
    "Royaume-Uni: ": "Londres",
    "Russie: ": "Moscou",
    "Rwanda: ": "Kigali",
    "Saint-Kitts-et-Nevis: ": "Basseterre",
    "Saint-Lucie: ": "Castries",
    "Saint-Vincent-et-les-Grenadines: ": "Kingstown",
    "Saint-Marin: ": "Saint-Marin",
    "Sao Tomé-et-Principe: ": "Sao Tome",
    "Arabie saoudite": "Riyad",
    "Sénégal: ": "Dakar",
    "Serbie: ": "Belgrade",
    "Seychelles: ": "Victoria",
    "Sierra Leone: ": "Freetown",
    "Singapour: ": "Singapour",
    "Slovaquie: ": "Bratislava",
    "Slovénie: ": "Ljubljana",
    "Solomon: ": "Honiara",
    "Somalie: ": "Mogadiscio",
    "Soudan: ": "Khartoum",
    "Soudan du Sud: ": "Djouba",
    "Espagne: ": "Madrid",
    "Sri Lanka: ": "Colombo",
    "Suède: ": "Stockholm",
    "Suisse: ": "Berne",
    "Suriname: ": "Paramaribo",
    "Swaziland: ": "Mbabane",
    "Syrie: ": "Damas",
    "Taiwan: ": "Taipei",
    "Tajikistan: ": "Douchanbé",
    "Tanzanie: ": "Dodoma",
    "Thaïlande: ": "Bangkok",
    "Togo: ":"Lomé",
    "Tonga: ": "Nuku'alofa",
    "Trinité-et-Tobago: ": "Port-d'Espagne",
    "Tunisie: ": "Tunis",
    "Turquie: ": "Ankara",
    "Turkménistan: ": "Achgabat",
    "Tuvalu: ": "Funafuti",
    "Ouganda: ": "Kampala",
    "Ukraine: ":"Kiev",
    "Uruguay: ": "Montevideo",
    "Ouzbékistan: ": "Tachkent",
    "Vanuatu: ": "Port Vila",
    "Venezuela: ": "Caracas",
    "Viêt Nam: ": "Hanoï",
    "Yémen": "Sanaa",
    "ZAMBIE: ":"LUSAKA",
    "ZIMBABWE: ":"HARARE"
}


ListPaysOne = {
    "JAPON: ":"TOKYO",
    "CHINE: ":"PEKIN",
    "ESPAGNE: ":"MADRID",
    "ZAMBIE: ":"LUSAKA",
    "CANADA: ":"OTTAWA",
    "TCHAD: ":"DJAMENA",
    "REPUBLIQUE DEMOCRATIQUE DU CONGO: ":"KINSHASA",
    "ROYAUME UNIS: ":"LONDRES",
    "ALLEMAGNE: ":"BERLIN",
    "Nigeria: ": "Abuja",
    "Grèce": "Athènes",
    "GABON: ":"LIBREVILLE"
}

ListPaysTwo = {
    "CÔTE D’IVOIRE: ":"YAMOUSSOUKRO",
    "Uruguay: ": "Montevideo",
    "ARGENTINE: ":"BUENOS AIRES",
    "CORÉE DU SUD: ":"SÉOUL",
    "ÉRYTHRÉE: ":"ASMARA",
    "COLOMBIE: ":"BOGOTA",
    "IRAK: ":"BAGDAD",
    "LIBYE: ":"TRIPOLI",
    "PAYS-BAS: ":"AMSTERDAM",
    "SOUDAN DU SUD: ":"DJOUBA",
    "Danemark": "Copenhague",
    "Maroc: ": "Rabat",
    "THAÏLANDE: ":"BANGKOK"
}

ListPaysThree = {
    "FINLANDE: ":"HELSINKI",
    "GAMBIE: ":"BANJUL",
    "GÉORGIE: ":"BILISSI",
    "GRÈCE: ":"ATHÈNES",
    "GRENADE: ":"SAINT-GEORGES",
    "GUATEMALA: ":"GUATEMALA",
    "GUINÉE: ":"CONAKRY",
    "GUYANA: ":"GEORGETOWN",
    "HAÏTI: ":"PORT-AU-PRINCE",
    "HONGRIE: ":"BUDAPEST"



}